#
# Copyright (c) 2015-2016 Sam4Mobile
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
# Customize Kitchen with some monkey patching:
# - Suites scheduler
#   <% require "#{File.dirname(__FILE__)}/test/kitchen_command.rb" %>
# - Alias to have shorter lines
#   <% ip_of = "docker inspect --format '{{.NetworkSettings.IPAddress}}'" %>

driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: chef_zero
  client_rb:
    file_atomic_update: false

platforms:
  - name: centos-7
    driver_config:
      image: sbernard/centos-systemd-kitchen
      volume: /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd

suites:
  # Install a ddns server
  - name: server
    driver:
      hostname: server-ddns.chef.kitchen
      container_name: server-ddns
    run_list:
      - recipe[bind-ddns]
    attributes:
      bind-ddns:
        servers: [ server-ddns.chef.kitchen ]
        set_resolv_conf: true
        server: localhost
        secondary_servers:
          - "8.8.8.8"
          - "8.8.4.4"
        search: chef.kitchen
        server-config: # Should be used
          options:
            listen-on: "port 53 { localnets; }"
            allow-query: "{ localnets; }"
        client-config: # Should not be used
          options:
            listen-on: "port 57"
            allow-query: "{ any; }"
        zones:
          - name: chef.kitchen
            config:
              type: master
              file: dynamic/db-chef-kitchen
              allow-update: "{ key chef.kitchen; }"
            ns: [ ns.chef.kitchen. ]
            a:
              ns.chef.kitchen.: eth0
        keys:
          - name: chef.kitchen
            secret: 9ZDQZxLEBuho4+O0EuGOYA==
        records:
          - data: eth0
          - domain: test-delete.chef.kitchen
            data: "1.2.3.4"

  - name: client
    driver:
      hostname: client-ddns.chef.kitchen
      container_name: client-ddns
      dns: $(<%= ip_of %> server-ddns)
    run_list:
      - recipe[bind-ddns]
    attributes:
      bind-ddns:
        servers: [ server-ddns.chef.kitchen ]
        keys:
          - name: chef.kitchen
            secret: 9ZDQZxLEBuho4+O0EuGOYA==
        client-config: # Should be used
         records:
            - zone: chef.kitchen
            - domain: "linux.client-ddns.chef.kitchen"
              data: "10.11.12.13"
              zone: chef.kitchen
            - domain: test-delete.chef.kitchen
              zone: chef.kitchen.
              keyname: chef.kitchen
              secret: 9ZDQZxLEBuho4+O0EuGOYA==
              action: delete
        server-config: # Should not be used
          set_resolv_conf: true
          server: localhost
          keys:
            - name: chef.kitchen
              secret: fakekey
